version: '3'

services:
  goapp-a:
    build:
      context: .
      dockerfile: Dockerfile.servicea
    ports:
      - "8181:8181"
    volumes:
      - .:/app
    environment:
      - SERVICE_B_ADDRESS=goapp-b:8080
      - WEB_SERVER_PORT=:8181
  
  goapp-b:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - WEB_SERVER_PORT=:8080